# version: "3.8"
services:
  backend:
    image: ayoubtir/backend:latest
    ports:
      - "3001:3001"

  frontend:
    image: ayoubtir/frontend:latest
    ports:
      - "3000:3000"

# Adding comment to test merge from deature to dev